
version: 2.1

# orbs:
#     hello: circleci/hello-build@0.0.7 # uses the circleci/buildpack-deps Docker image

jobs:
  build:
    docker: # use the docker executor type; machine and macos executors are also supported
      - image: circleci/node:10.14-browsers

    working_directory: ~/circlci

    steps:
      - checkout # check out the code in the project directory
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      
      - run: yarn test
      - run: yarn ecommerce

      - store_test_results:
          path: /tmp/test-results

workflows:
    "TestCafe Example Work flow":
        jobs:
          - build
